codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_not_found: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.config.*"
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/__tests__/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/__mocks__/**"
  - "**/__fixtures__/**"
